# Site
name: "GLUG MVIT"
title: "GLUG MVIT"
description: "Community of FOSS developers from Sir M. Visvesvaraya Institute of Technology"
meta_description: "Technical community at Sir MVIT, Bangalore"
logo: 'assets/images/logo_full_rect.png'
favicon: 'assets/images/favicon.ico'
baseurl:
email: 'glugmvit@gmail.com'
# google_analytics: 'UA-46278016-1'
disqus: 'glugmvit'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  absingh:
    name: Abhijeet Singh
    display_name: Abhijeet Singh
    gravatar: "https://www.gravatar.com/avatar/a737e0e0b617487e706c406b0b80ef5d?s=250&d=mm&r=x"
    email: contact.abhijeetsingh@gmail.com
    web: https://www.absingh.com
    twitter: https://twitter.com/cse_as
    description: "Neighbourhood friendly Software Engineer. GLUG Lead | Microsoft Student Partner | AI Developer"
  vipul:
    name: Vipul Gaurav
    display_name: Vipul Gaurav
    gravatar: "/assets/images/avatar/vipul.jpeg"
    email: vgaurav3011@gmail.com
    web: https://www.linkedin.com/in/vipul-gaurav/
    twitter: https://twitter.com/username
    description: "MLH representative and Smart India Hackathon winner 2019"
  vhr:
    name: Veeresh H R
    display_name: Veeresh H R
    gravatar: "/assets/images/avatar/vhr.jpeg"
    email: veereshhr121@gmail.com
    web: https://vhr121.github.io/
    twitter: https://twitter.com/vhr121
    description: "Machine Learning Engineer, Full stack Developer, Tech Speaker, FOSS Enthusiast, Traveller and Biker. Founder of GLUG MVIT."
  harsh:
    name: Harsh Gahlot
    display_name: Harsh Gahlot
    gravatar: "https://www.gravatar.com/avatar/609075465595e233f1e062f70a76566b?s=250&d=mm&r=x"
    email: harshghlt25@gmail.com
    web: https://euno257.github.io
    twitter: https://twitter.com/Hersh257
    description: "Web Developer | Machine Learning Developer | Tech Speaker"
  sunchit:
    name: Sunchit Lakhanpal
    display_name: Sunchit Lakhanpal
    gravatar: "https://www.gravatar.com/avatar/a9b01bf4da44670301874b50f8245eca?s=250&d=mm&r=x"
    email: lakhanpalsunchit8@gmail.com
    web: https://sunchit17.github.io
    twitter: https://twitter.com/SLakhanpal17
    description: "Java | Android | Flutter | Django Developer | Tech Speaker"
  ayushi:
    name: Ayushi
    display_name: Ayushi
    gravatar: "/assets/images/avatar/ayushi.png"
    email: ayushi2712@gmail.com
    web: https://ayushianan.github.io
    twitter: https://twitter.com/Ayushi21084272
    description: "Web Developer, Machine Learning Engineer, Tech Speaker"
  masoomi:
    name: Masoomi Saxena
    display_name: Masoomi Saxena
    gravatar: "https://www.gravatar.com/avatar/a9b01bf4da44670301874b50f8245eca?s=250&d=mm&r=x"
    email: lakhanpalsunchit8@gmail.com
    web: https://sunchit17.github.io
    twitter: https://twitter.com/SLakhanpal17
    description: "Java | Android | Flutter | Django Developer | Tech Speaker"
# Reading Files
include:
- _pages
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives


# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Conversion
markdown: kramdown
highlighter: rouge

# Output
permalink: /:title/
paginate: 6

sass:
    sass_dir: _sass
