# Site
name: "GLUG MVIT"
title: "GLUG MVIT"
description: "Community of FOSS developers from Sir M. Visvesvaraya Institute of Technology"
meta_description: "Technical community at Sir MVIT, Bangalore"
logo: 'assets/images/logo_full_rect.png'
favicon: 'assets/images/favicon.ico'
baseurl:
email: 'glugmvit@gmail.com'
# google_analytics: 'UA-46278016-1'
disqus: 'glugmvit'
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'
sharethis: "<script type='text/javascript' src='//platform-api.sharethis.com/js/sharethis.js#property=5cca329136d0970012b888ec&product=sticky-share-buttons' async='async'></script>"

# Authors
authors:
  absingh:
    name: Abhijeet Singh
    display_name: Abhijeet Singh
    gravatar: "https://www.gravatar.com/avatar/a737e0e0b617487e706c406b0b80ef5d?s=250&d=mm&r=x"
    email: contact.abhijeetsingh@gmail.com
    web: https://www.absingh.com
    twitter: https://twitter.com/cse_as
    description: "Neighbourhood friendly Software Engineer. GLUG Lead | Microsoft Student Partner | AI Developer"

  ayushi:
    name: Ayushi
    display_name: Ayushi
    gravatar: "/assets/images/avatar/ayushi.jpg"
    email: ayushi2712@gmail.com
    web: https://ayushianan.github.io
    twitter: https://twitter.com/Ayushi21084272
    description: "Web Developer, Machine Learning Engineer, Tech Speaker"

  harsh:
    name: Harsh Gahlot
    display_name: Harsh Gahlot
    gravatar: "https://www.gravatar.com/avatar/609075465595e233f1e062f70a76566b?s=250&d=mm&r=x"
    email: harshghlt25@gmail.com
    web: https://www.linkedin.com/in/hersh257/
    twitter: https://twitter.com/Hersh257
    description: "Microsoft Student Partner | Software Developer | Tech Speaker"

  sunchit:
    name: Sunchit Lakhanpal
    display_name: Sunchit Lakhanpal
    gravatar: "https://www.gravatar.com/avatar/a9b01bf4da44670301874b50f8245eca?s=250&d=mm&r=x"
    email: lakhanpalsunchit8@gmail.com
    web: https://sunchit17.github.io
    twitter: https://twitter.com/SLakhanpal17
    description: "Java | Android | Flutter | Django Developer | Tech Speaker"

  srishti:
    name: Srishti Nema
    display_name: Srishti Nema
    gravatar: "/assets/images/avatar/srishti.jpeg"
    email: srishtinema.0699@gmail.com
    web: https://www.linkedin.com/in/srishtinema/
    twitter: https://github.com/srishti-nema
    description: "Web Developer | Problem Solver | Filled with Ideas"

  masoomi:
    name: Masoomi Saxena
    display_name: Masoomi Saxena
    gravatar: "https://secure.gravatar.com/avatar/12225806f6a4dec7c55e5d2ea227137a?s=250&d=mm&r=x"
    email: masoomi.saxena99@gmail.com
    web: https://www.linkedin.com/in/masoomi-saxena-372b84172
    twitter: https://www.linkedin.com/in/masoomi-saxena-372b84172
    description: "Java | Web developer | Blogger"

  vipul:
    name: Vipul Gaurav
    display_name: Vipul Gaurav
    gravatar: "/assets/images/avatar/vipul.jpeg"
    email: vgaurav3011@gmail.com
    web: https://www.linkedin.com/in/vipul-gaurav/
    twitter: https://twitter.com/username
    description: "Self-taught Programmer. GLUG Lead|Data Scientist|Deep Learning"

  vhr:
    name: Veeresh H R
    display_name: Veeresh H R
    gravatar: "/assets/images/avatar/vhr.jpeg"
    email: veereshhr121@gmail.com
    web: https://vhr121.github.io/
    twitter: https://twitter.com/vhr121
    description: "Machine Learning Engineer, Full stack Developer, Tech Speaker, FOSS Enthusiast, Traveller and Biker. Founder of GLUG MVIT."

  sharjil:
    name: Syed Sharjil Ahmed
    display_name: Sharjil Ahmed
    gravatar: "/assets/images/avatar/sharjil.jpg"
    email: syedsharjil@outlook.com
    web: https://www.linkedin.com/in/syedsharjil/
    twitter: https://twitter.com/_syedsharjil_
    description: "Web Developer | Blogger | Chelsea Fanatic"

  shruti:
    name: Shruti Shukla
    display_name: Shruti Shukla
    gravatar: "/assets/images/avatar/shrutiss.jpg"
    email: shrutiss2511@gmail.com
    twitter: https://www.linkedin.com/in/shruti-shukla-156b21184
    web: https://shrutishuk.github.io
    description: "Web Developer | Problem Solver"

  susmit:
    name: Susmit Agrawal
    display_name: Susmit Agrawal
    gravatar: "/assets/images/avatar/susmit.jpg"
    email: susmit.agrawal.dev@gmail.com
    twitter: https://www.github.com/Susmit-A
    web: https://www.linkedin.com/in/susmit-agrawal-9b6443149
    description: "Deep Learning | Android | IoT"

  aditya:
    name: Aditya Raman
    display_name: Aditya Raman
    gravatar: "/assets/images/avatar/aditya.jpeg"
    email: adityaraman96@gmail.com
    twitter: https://twitter.com/_adityaraman
    web: https://ramanaditya.github.io
    description: "Software Developer | Engineer | Former Full Stack Developer Intern | Volunteer at UNV Online"

  prakruthi:
    name: Prakruthi Manjunath
    display_name: Prakruthi Maanjunath
    gravatar: "/assets/images/avatar/prakruthi.jpeg"
    email: prakruthim25@gmail.com
    twitter: https://twitter.com/Prakrut66322847
    web: https://prakruthi3.github.io
    description: "App Developer | Engineer | Reader"

  ujwal:
    name: Ujwal Kumar
    display_name: Ujwal Kumar
    gravatar: "/assets/images/avatar/ujwal.png"
    email: admin@ujwalkr.com
    twitter: https://twitter.com/Ujwal07kumar?s=03
    web: https://ujwalkr.com
    description: "Developer | Web, Mobile & API Security | Mentor"

  shashwat:
    name: Shashwat Srivastava
    display_name: Shashwat Srivastava
    gravatar: "/assets/images/avatar/shashwat.jpeg"
    email: shanu.sri0212@gmail.com
    twitter: https://www.instagram.com/shashwat.0212/
    web:
    description: "Proficient in Java, C++ and OOP | Problem Solving Enthusiast"

  shresth:
    name: Shresth Singh
    display_name: Shresth Singh
    gravatar: "/assets/images/avatar/shresth.jpeg"
    email: singhshresth26@gmail.com
    twitter: https://www.instagram.com/shresth_sing/
    web: https://www.linkedin.com/in/shresth-singh-7aa062175/
    description: "Artificial Intelligence | Machine Learning"

  avikant:
    name: Avikant Srivastava
    display_name: Avikant Srivastava
    gravatar: "/assets/images/avatar/avikant.jpeg"
    email: asdavikant@gmail.com
    twitter: https://www.instagram.com/aesthetixell/
    web: https://avikant.works/
    description: "Proficient in Python | Junior ML Engineer at Omdena"

  aswin:
    name: Aswin Gopinathan
    display_name: Aswin Gopinathan
    gravatar: "https://en.gravatar.com/userimage/144557467/450f60b0158d58a58db780b9a5a91055.png?size=200"
    email: aswingopinathan1871@gmail.com
    web: https://www.linkedin.com/in/aswin-gopinathan-69556716a/
    twitter: https://twitter.com/GopinathanAswin
    description: "Python | Machine Learning | Android"


# Reading Files
include:
- _pages
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Output
permalink: /:title/

# Pagination
paginate: 12
paginate_path: /page:num/

# Markdown Processing
markdown: kramdown
# Conversion
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  footnote_nr: 1
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

sass:
    sass_dir: _sass

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
